from uuid import uuid4
from typing import Dict, Any, cast
from logging import getLogger

from agent_network.agents.worker.shemas import Context, State, InputState
from agent_network.agents.worker.graph import builder
from agent_network.config import get_settings

logger = getLogger(__name__)

def execute_worker_agent(task: str) -> str:
    logger.info("Starting worker agent …")

    graph = builder.compile()

    graph_input =InputState(task=task)

    context = Context(model=get_settings().LLM_MODEL_NAME)

    configuration = {"thread_id": str(uuid4()), "user_id": str(uuid4())}

    result = cast(State, graph.invoke(input=graph_input, context=context, 
                                    configuration={"configurable": configuration, "recursion_limit": 10}))

    logger.info(f"Graph execution completed")

    result = result["messages"][-1].content if len(result["messages"]) > 0 else "No response generated by the agent."

    logger.info(f"Worker agent result: {result}")

    result_text = str(result[-0]["text"]).strip() if result else ""

    return result_text
